config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                  Controller#Action
#         root GET    /                            pages#index
#        users POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#    edit_user GET    /users/:id/edit(.:format)    users#edit
#         user PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#     projects GET    /projects(.:format)          projects#index
#              POST   /projects(.:format)          projects#create
#  new_project GET    /projects/new(.:format)      projects#new
# edit_project GET    /projects/:id/edit(.:format) projects#edit
#      project PATCH  /projects/:id(.:format)      projects#update
#              PUT    /projects/:id(.:format)      projects#update
#              DELETE /projects/:id(.:format)      projects#destroy
#        tasks GET    /tasks(.:format)             tasks#index
#              POST   /tasks(.:format)             tasks#create
#     new_task GET    /tasks/new(.:format)         tasks#new
#    edit_task GET    /tasks/:id/edit(.:format)    tasks#edit
#         task PATCH  /tasks/:id(.:format)         tasks#update
#              PUT    /tasks/:id(.:format)         tasks#update
#              DELETE /tasks/:id(.:format)         tasks#destroy
#    dashboard GET    /dashboard(.:format)         projects#index
#        login GET    /login(.:format)             session#new
#              POST   /login(.:format)             session#create
#              DELETE /login(.:format)             session#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#index'
  resources :users, :only => [:new, :create, :edit, :update]
  resources :projects, :except => [:show]
  resources :tasks, :except => [:show]
  get '/dashboard' => 'projects#index'

  get 'projects/:id/member/add' => 'projects#add_member'
  post 'projects/member/add' => 'projects#save_members'

  # Check with Joel what method these should be
  post 'tasks/take' => 'tasks#take'
  post 'tasks/release' => 'tasks#release'
  post 'tasks/complete' => 'tasks#complete'
  post 'tasks/reopen' => 'tasks#reopen'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AvantisApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

  <body>

  <header>
    <div class="header-wrapper">
      <div class="logo">
        <%= link_to image_tag('logo-white.png') , root_path %>
      </div>
      <nav>
        <%= link_to "Home", root_path, :class => 'menu-item' %>
        <% if @current_user.present? %>
          <%= link_to @current_user.name, edit_user_path(@current_user), :class => 'menu-item'  %>
          <%= link_to "Dashboard", dashboard_path, :class => 'menu-item'  %>
          <%= link_to "Logout", login_path, :method => 'delete', :class => 'menu-item'%>
        <% else %>
          <%= link_to "Sign Up", new_user_path, :class => 'menu-item' %>
          <%= link_to "Sign In", login_path, :class => 'menu-item' %>
        <% end %>
      </nav>
      <div id="toggle">
        <div class="span" id="one"></div>
        <div class="span" id="two"></div>
        <div class="span" id="three"></div>
      </div>
      <div id="resize">
        <nav>
          <%= link_to "Home", root_path, :class => 'menu-item' %>
          <% if @current_user.present? %>
            <%= link_to @current_user.name, edit_user_path(@current_user), :class => 'menu-item'  %>
            <%= link_to "Dashboard", dashboard_path, :class => 'menu-item'  %>
            <%= link_to "Logout", login_path, :method => 'delete', :class => 'menu-item'%>
          <% else %>
            <%= link_to "Sign Up", new_user_path, :class => 'menu-item' %>
            <%= link_to "Sign In", login_path, :class => 'menu-item' %>
          <% end %>
        </nav>
      </div>
    </div>
  </header>

  <main>
    <%= yield %>
  </main>


  <footer>
    <div class="footer-wrapper">
      <p>&copy; 2017 developed by <a href="https://github.com/dansyd">Daniele Peviani</a></p>
    </div>
  </footer>

</body>

</html>